name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs:
  build_and_push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: josecyber/contacts-api:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_and_push_to_registry
    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y ssh

      - name: Connect via SSH and Update Docker Image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/server/contacts-api
            sed -i 's/image: josecyber\/contacts-api:.*/image: josecyber\/contacts-api:${{ github.sha }}/' contacts-api.yaml
            docker compose -f contacts-api.yaml up -d